// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/container.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContainerAdmService_GetContainerInformation_FullMethodName = "/container_adm_service.ContainerAdmService/GetContainerInformation"
)

// ContainerAdmServiceClient is the client API for ContainerAdmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerAdmServiceClient interface {
	GetContainerInformation(ctx context.Context, in *GetContainerInformationRequest, opts ...grpc.CallOption) (*GetContainerInformationResponse, error)
}

type containerAdmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerAdmServiceClient(cc grpc.ClientConnInterface) ContainerAdmServiceClient {
	return &containerAdmServiceClient{cc}
}

func (c *containerAdmServiceClient) GetContainerInformation(ctx context.Context, in *GetContainerInformationRequest, opts ...grpc.CallOption) (*GetContainerInformationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerInformationResponse)
	err := c.cc.Invoke(ctx, ContainerAdmService_GetContainerInformation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerAdmServiceServer is the server API for ContainerAdmService service.
// All implementations must embed UnimplementedContainerAdmServiceServer
// for forward compatibility.
type ContainerAdmServiceServer interface {
	GetContainerInformation(context.Context, *GetContainerInformationRequest) (*GetContainerInformationResponse, error)
	mustEmbedUnimplementedContainerAdmServiceServer()
}

// UnimplementedContainerAdmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContainerAdmServiceServer struct{}

func (UnimplementedContainerAdmServiceServer) GetContainerInformation(context.Context, *GetContainerInformationRequest) (*GetContainerInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainerInformation not implemented")
}
func (UnimplementedContainerAdmServiceServer) mustEmbedUnimplementedContainerAdmServiceServer() {}
func (UnimplementedContainerAdmServiceServer) testEmbeddedByValue()                             {}

// UnsafeContainerAdmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerAdmServiceServer will
// result in compilation errors.
type UnsafeContainerAdmServiceServer interface {
	mustEmbedUnimplementedContainerAdmServiceServer()
}

func RegisterContainerAdmServiceServer(s grpc.ServiceRegistrar, srv ContainerAdmServiceServer) {
	// If the following call pancis, it indicates UnimplementedContainerAdmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContainerAdmService_ServiceDesc, srv)
}

func _ContainerAdmService_GetContainerInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerAdmServiceServer).GetContainerInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerAdmService_GetContainerInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerAdmServiceServer).GetContainerInformation(ctx, req.(*GetContainerInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerAdmService_ServiceDesc is the grpc.ServiceDesc for ContainerAdmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerAdmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "container_adm_service.ContainerAdmService",
	HandlerType: (*ContainerAdmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContainerInformation",
			Handler:    _ContainerAdmService_GetContainerInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/container.proto",
}
